#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuGetGallery.Views.Packages
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Packages/DisplayPackage.cshtml")]
    public class DisplayPackage : System.Web.Mvc.WebViewPage<DisplayPackageViewModel>
    {
        public DisplayPackage()
        {
        }
        public override void Execute()
        {


            
            #line 2 "..\..\Views\Packages\DisplayPackage.cshtml"
  
    ViewBag.Tab = "Packages";


            
            #line default
            #line hidden
WriteLiteral("<div id=\"layout-main\" class=\"group\">\n    <div id=\"layout-content\" class=\"group\">\n" +
"");


            
            #line 7 "..\..\Views\Packages\DisplayPackage.cshtml"
         if (TempData.ContainsKey("Message")) {

            
            #line default
            #line hidden
WriteLiteral("            <div id=\"messages\">\n                <div class=\"zone zone-messages\">\n" +
"                    <div class=\"message message-Information\">");


            
            #line 10 "..\..\Views\Packages\DisplayPackage.cshtml"
                                                        Write(TempData["Message"]);

            
            #line default
            #line hidden
WriteLiteral("</div>\n                </div>\n            </div>\n");


            
            #line 13 "..\..\Views\Packages\DisplayPackage.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral(@"        <div id=""content"" class=""group"">
            <div class=""zone zone-content"">
                <section class=""packageItemDetail icon"">
                    <div id=""thumbnails"">
                        <div class=""packageLogo"">
                            <img src=""");


            
            #line 19 "..\..\Views\Packages\DisplayPackage.cshtml"
                                  Write(Model.IconUrl ?? @Links.Content.Images.packageDefaultIcon_png);

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"Icon for package ");


            
            #line 19 "..\..\Views\Packages\DisplayPackage.cshtml"
                                                                                                                         Write(Model.Id);

            
            #line default
            #line hidden
WriteLiteral("\" />\n                        </div>\n                    </div>\n                  " +
"  <div>\n                        <header>\n                            <div class=" +
"\"title\">\n                                <h2>");


            
            #line 25 "..\..\Views\Packages\DisplayPackage.cshtml"
                               Write(Model.Title);

            
            #line default
            #line hidden
WriteLiteral("</h2>\n                                <h3>\n                                    ");


            
            #line 27 "..\..\Views\Packages\DisplayPackage.cshtml"
                               Write(Model.Version);

            
            #line default
            #line hidden
WriteLiteral("\n");


            
            #line 28 "..\..\Views\Packages\DisplayPackage.cshtml"
                                     if (Model.Prerelease) { 

            
            #line default
            #line hidden
WriteLiteral("                                    <span class=\"prerelease\">Prerelease</span>\n");


            
            #line 30 "..\..\Views\Packages\DisplayPackage.cshtml"
                                    }
                                    else if (Model.LatestVersion) {

            
            #line default
            #line hidden
WriteLiteral("                                        <span class=\"latest\">Latest Version</span" +
">\n");


            
            #line 33 "..\..\Views\Packages\DisplayPackage.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                </h3>\n                            </div>\n        " +
"                    <div class=\"description\">\n                                <p" +
">\n                                    ");


            
            #line 38 "..\..\Views\Packages\DisplayPackage.cshtml"
                               Write(Model.Description);

            
            #line default
            #line hidden
WriteLiteral("\n                                </p>\n");


            
            #line 40 "..\..\Views\Packages\DisplayPackage.cshtml"
                                 if (!Model.Listed && Model.IsOwner(User)) {

            
            #line default
            #line hidden
WriteLiteral(@"                                    <div class=""zone-messages"">
                                        <div class=""message message-Warning"">
                                            This package is unlisted and hidden from package listings.
                                        
                                            <p class=""note"">
                                                You can see the package because you are one of its owners. 
                                                To display the package in search results and the package feed, 
                                                <a class=""edit"" href=""");


            
            #line 48 "..\..\Views\Packages\DisplayPackage.cshtml"
                                                                 Write(Url.EditPackage(Model));

            
            #line default
            #line hidden
WriteLiteral("\">edit the package</a>.\n                                            </p>\n        " +
"                                </div>\n                                        \n" +
"                                    </div>\n");


            
            #line 53 "..\..\Views\Packages\DisplayPackage.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                                <p>\n                                    To instal" +
"l ");


            
            #line 55 "..\..\Views\Packages\DisplayPackage.cshtml"
                                          Write(Model.Title);

            
            #line default
            #line hidden
WriteLiteral(@", run the following command from the command line or from PowerShell:
                                    <div class=""commandWrapper"">
                                        <div class=""commandPrompt"">
                                            <p class=""command"">C:\&gt; cinst ");


            
            #line 58 "..\..\Views\Packages\DisplayPackage.cshtml"
                                                                        Write(Model.Id);

            
            #line default
            #line hidden

            
            #line 58 "..\..\Views\Packages\DisplayPackage.cshtml"
                                                                                        if (!Model.LatestVersion) {
            
            #line default
            #line hidden
WriteLiteral(" -version ");


            
            #line 58 "..\..\Views\Packages\DisplayPackage.cshtml"
                                                                                                                              Write(Model.Version);

            
            #line default
            #line hidden

            
            #line 58 "..\..\Views\Packages\DisplayPackage.cshtml"
                                                                                                                                                        }
            
            #line default
            #line hidden
WriteLiteral(@"</p>
                                        </div>
                                    </div>
                                </p>
                            </div>
                        </header>
                                        
                        <h4 class=""details-header"">Packages details</h4>
");


            
            #line 66 "..\..\Views\Packages\DisplayPackage.cshtml"
                         if (Model.IsOwner(User)) {

            
            #line default
            #line hidden
WriteLiteral("                            <div class=\"package-owner-actions\">\n                 " +
"               <ul>\n                                    <li><a class=\"edit\" href" +
"=\"");


            
            #line 69 "..\..\Views\Packages\DisplayPackage.cshtml"
                                                         Write(Url.EditPackage(Model));

            
            #line default
            #line hidden
WriteLiteral("\">Edit</a></li>\n                                    <li><a class=\"manage-owners\" " +
"href=\"");


            
            #line 70 "..\..\Views\Packages\DisplayPackage.cshtml"
                                                                  Write(Url.ManagePackageOwners(Model));

            
            #line default
            #line hidden
WriteLiteral("\">Manage Owners</a></li>\n                                    <li><a href=\"");


            
            #line 71 "..\..\Views\Packages\DisplayPackage.cshtml"
                                            Write(Url.DeletePackage(Model));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"delete\">Delete</a></li>\n                                </ul>\n          " +
"                  </div>\n");


            
            #line 74 "..\..\Views\Packages\DisplayPackage.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                        <ul class=\"links\">\n");


            
            #line 76 "..\..\Views\Packages\DisplayPackage.cshtml"
                             if (!String.IsNullOrEmpty(Model.ProjectUrl)) {

            
            #line default
            #line hidden
WriteLiteral("                                <li><a href=\"");


            
            #line 77 "..\..\Views\Packages\DisplayPackage.cshtml"
                                        Write(Model.ProjectUrl);

            
            #line default
            #line hidden
WriteLiteral("\" title=\"Visit the project site to learn more about this package\">\n              " +
"                      Project site</a></li>\n");


            
            #line 79 "..\..\Views\Packages\DisplayPackage.cshtml"
                            }

            
            #line default
            #line hidden

            
            #line 80 "..\..\Views\Packages\DisplayPackage.cshtml"
                             if (!String.IsNullOrEmpty(Model.LicenseUrl)) {

            
            #line default
            #line hidden
WriteLiteral("                                <li><a href=\"");


            
            #line 81 "..\..\Views\Packages\DisplayPackage.cshtml"
                                        Write(Model.LicenseUrl);

            
            #line default
            #line hidden
WriteLiteral("\" title=\"Make sure you agree with the license\">License</a></li>\n");


            
            #line 82 "..\..\Views\Packages\DisplayPackage.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                            <li><a href=\"");


            
            #line 83 "..\..\Views\Packages\DisplayPackage.cshtml"
                                    Write(Url.Action(MVC.Packages.ReportAbuse(Model.Id, Model.Version)));

            
            #line default
            #line hidden
WriteLiteral("\" title=\"Report Abuse\">Report Abuse</a></li>\n                            <li><a h" +
"ref=\"");


            
            #line 84 "..\..\Views\Packages\DisplayPackage.cshtml"
                                    Write(Url.Action(MVC.Packages.ContactOwners(Model.Id)));

            
            #line default
            #line hidden
WriteLiteral("\">Contact Owners</a></li>\n                            <li><a href=\"");


            
            #line 85 "..\..\Views\Packages\DisplayPackage.cshtml"
                                    Write(Url.PackageDownload(Model.Id, Model.Version));

            
            #line default
            #line hidden
WriteLiteral("\">Download</a></li>\n                        </ul>\n\n                        ");


            
            #line 88 "..\..\Views\Packages\DisplayPackage.cshtml"
                   Write(Html.Partial("_PackageDetailsTable", Model));

            
            #line default
            #line hidden
WriteLiteral("\n\n                        <div class=\"stats\">\n                            <span c" +
"lass=\"downloads\">\n                                <strong>");


            
            #line 92 "..\..\Views\Packages\DisplayPackage.cshtml"
                                   Write(Model.TotalDownloadCount);

            
            #line default
            #line hidden
WriteLiteral("</strong>\n                                <label>total downloads</label>\n        " +
"                    </span>\n                            <span class=\"downloads\">" +
"\n                                <strong>");


            
            #line 96 "..\..\Views\Packages\DisplayPackage.cshtml"
                                   Write(Model.DownloadCount);

            
            #line default
            #line hidden
WriteLiteral("</strong>\n                                <label>for this version</label>\n       " +
"                     </span>\n                        </div>\n\n                   " +
"     <h4 class=\"details-header\">Dependencies</h4>\n");


            
            #line 102 "..\..\Views\Packages\DisplayPackage.cshtml"
                         if (Model.Dependencies.Any()) {

            
            #line default
            #line hidden
WriteLiteral(@"                            <table class=""packages dependencies"">
                                <thead>
                                    <tr class=""header"">
                                        <th style=""width: 10%;"">Id</th>
                                        <th class=""version"">Version Range</th>
                                    </tr>
                                </thead>
");


            
            #line 110 "..\..\Views\Packages\DisplayPackage.cshtml"
                             foreach (var dependency in Model.Dependencies) {

            
            #line default
            #line hidden
WriteLiteral("                                <tr>\n                                    <td styl" +
"e=\"width: auto;\"><a href=\"");


            
            #line 112 "..\..\Views\Packages\DisplayPackage.cshtml"
                                                                 Write(Url.Package(dependency.Id));

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 112 "..\..\Views\Packages\DisplayPackage.cshtml"
                                                                                              Write(dependency.Id);

            
            #line default
            #line hidden
WriteLiteral("</a></td>\n                                    <td>");


            
            #line 113 "..\..\Views\Packages\DisplayPackage.cshtml"
                                   Write(dependency.VersionSpec);

            
            #line default
            #line hidden
WriteLiteral("</td>\n                                </tr>\n");


            
            #line 115 "..\..\Views\Packages\DisplayPackage.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                            </table>\n");


            
            #line 117 "..\..\Views\Packages\DisplayPackage.cshtml"
                        }
                        else {

            
            #line default
            #line hidden
WriteLiteral("                            <div class=\"dependencies\">\n                          " +
"      <em>No Dependencies</em>\n                            </div>\n");


            
            #line 122 "..\..\Views\Packages\DisplayPackage.cshtml"
                        }                            

            
            #line default
            #line hidden
WriteLiteral(@"                        <h4 class=""details-header"">Version history</h4>
                        <table class=""packages"" cellpadding=""0"" cellspacing=""0"">
                            <thead>
                                <tr class=""header"">
                                    <th class=""version"">
                                        Version
                                    </th>
                                    <th class=""downloads"">
                                        Downloads
                                    </th>
                                    <th class=""lastUpdated"">
                                        Last updated
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
");


            
            #line 139 "..\..\Views\Packages\DisplayPackage.cshtml"
                                 foreach (var packageVersion in Model.PackageVersions) {

            
            #line default
            #line hidden

            
            #line 140 "..\..\Views\Packages\DisplayPackage.cshtml"
WriteLiteral("                                    <tr class=\"versionTableRow ");

            
            #line default
            #line hidden
            
            #line 140 "..\..\Views\Packages\DisplayPackage.cshtml"
                                                                if (packageVersion.LatestVersion) {
            
            #line default
            #line hidden
WriteLiteral("recommended ");


            
            #line 140 "..\..\Views\Packages\DisplayPackage.cshtml"
                                                                                                                            }
            
            #line default
            #line hidden

            
            #line 140 "..\..\Views\Packages\DisplayPackage.cshtml"
                                                                                                                               if (packageVersion.IsCurrent(Model)) {
            
            #line default
            #line hidden
WriteLiteral("current");


            
            #line 140 "..\..\Views\Packages\DisplayPackage.cshtml"
                                                                                                                                                                                         }
            
            #line default
            #line hidden

            
            #line 140 "..\..\Views\Packages\DisplayPackage.cshtml"
                                                                                                                                                                                          WriteLiteral(" \">\n                                        <td class=\"version\" ");

            
            #line default
            #line hidden
            
            #line 141 "..\..\Views\Packages\DisplayPackage.cshtml"
                                                             if (packageVersion.LatestVersion) {
            
            #line default
            #line hidden
WriteLiteral("title=\"Latest Version\"");


            
            #line 141 "..\..\Views\Packages\DisplayPackage.cshtml"
                                                                                                                                   }
            
            #line default
            #line hidden
WriteLiteral(">\n");


            
            #line 142 "..\..\Views\Packages\DisplayPackage.cshtml"
                                             if (!packageVersion.IsCurrent(Model)) {

            
            #line default
            #line hidden
WriteLiteral("                                                <a href=\"");


            
            #line 143 "..\..\Views\Packages\DisplayPackage.cshtml"
                                                    Write(Url.Package(packageVersion));

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 143 "..\..\Views\Packages\DisplayPackage.cshtml"
                                                                                  Write(packageVersion.Title);

            
            #line default
            #line hidden
WriteLiteral(" ");


            
            #line 143 "..\..\Views\Packages\DisplayPackage.cshtml"
                                                                                                        Write(packageVersion.Version);

            
            #line default
            #line hidden
WriteLiteral("</a>\n");


            
            #line 144 "..\..\Views\Packages\DisplayPackage.cshtml"
                                            }
                                            else {

            
            #line default
            #line hidden
WriteLiteral("                                                <span>");


            
            #line 146 "..\..\Views\Packages\DisplayPackage.cshtml"
                                                 Write(packageVersion.Title);

            
            #line default
            #line hidden
WriteLiteral(" ");


            
            #line 146 "..\..\Views\Packages\DisplayPackage.cshtml"
                                                                       Write(packageVersion.Version);

            
            #line default
            #line hidden
WriteLiteral("</span>\n");


            
            #line 147 "..\..\Views\Packages\DisplayPackage.cshtml"
                                            }

            
            #line default
            #line hidden
WriteLiteral("                                        </td>\n                                   " +
"     <td class=\"downloads\">");


            
            #line 149 "..\..\Views\Packages\DisplayPackage.cshtml"
                                                         Write(packageVersion.DownloadCount);

            
            #line default
            #line hidden
WriteLiteral("\n                                        </td>\n                                  " +
"      <td class=\"lastUpdated\">");


            
            #line 151 "..\..\Views\Packages\DisplayPackage.cshtml"
                                                           Write(packageVersion.LastUpdated.ToString("D"));

            
            #line default
            #line hidden
WriteLiteral("\n                                        </td>\n                                  " +
"  </tr>\n");


            
            #line 154 "..\..\Views\Packages\DisplayPackage.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                            </tbody>\n                        </table>\n           " +
"         </div>\n                </section>\n            </div>\n        </div>\n   " +
" </div>\n</div>\n");


        }
    }
}
#pragma warning restore 1591
