#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuGetGallery.Views.Pages
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Pages/Home.cshtml")]
    public class Home : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Home()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Views\Pages\Home.cshtml"
  
    ViewBag.Tab = "Home";


            
            #line default
            #line hidden
WriteLiteral("<div id=\"layout-main\" class=\"group\">\n    <div id=\"layout-content\" class=\"group\">\n" +
"        <div id=\"content\" class=\"group\">\n            <div class=\"zone zone-conte" +
"nt\">\n                <article class=\"content-item page\">\n                    <h1" +
" style=\"font-size: 25px; font-weight: bold; color:red; text-shadow: rgba(0,0,0,." +
"1) 0px 0px 1px;\">NOTE: This gallery is still a work in progress, bear with us!</" +
"h1>\n                    <h2 style=\"font-size: 25px; font-weight: normal; text-sh" +
"adow: rgba(0,0,0,.1) 0px 0px 1px;\">You are getting an early preview. The client " +
"works, the site show packages and other information.</h2>\n                    <d" +
"iv class=\"MIX-hero\">\n                        <div class=\"MIX-hero-text\">\n       " +
"                     <h2 style=\"font-size: 25px; font-weight: normal; text-shado" +
"w: rgba(0,0,0,.1) 0px 0px 1px;\">Let\'s get chocolatey!</h2>\n                     " +
"       <p style=\"font-size: 18px; line-height: 30px;\">Chocolatey NuGet is a Mach" +
"ine Package Manager, somewhat like apt-get, but built with windows in mind.</p>\n" +
"                            <!--<p><span class=\"install\" style=\"margin: 42px 0 0" +
" 0;\">Install Chocolatey</span></p>-->\n                            <h2>Easy Insta" +
"ll!</h2>\n                            <p style=\"font-size: 16px;\">To install choc" +
"olatey now, open a powershell prompt (execution policy needs to be unrestricted)" +
", paste the following and type Enter: \n                            </p>\n        " +
"                </div>\n                        <div>\n                          <" +
"div class=\"commandWrapper\">\n                            <div class=\"commandPromp" +
"t\">\n                              <p class=\"command\">PS:\\&gt; iex ((new-object n" +
"et.webclient).DownloadString(\"http://bit.ly/psChocInstall\"))</p>\n               " +
"             </div>\n                          </div>\n                        </d" +
"iv>\n                      </div>\n                </article>  \n            </div>" +
"\n        </div>\n    </div>\n    <div id=\"layout-after-main\" class=\"group\">\n      " +
"  <div class=\"zone zone-after-main\">\n            <article class=\"widget-html-wid" +
"get widget\">\n                <div class=\"MIX-secondary group\">\n                 " +
"   <div style=\"float: left; width: 470px; margin: 0 0 24px 0;\">\n                " +
"        <h3 style=\"font-size: 18px; font-weight: normal;\">About</h3>\n           " +
"             <p style=\"font-size: 14px; line-height: 26px;\">When you use chocola" +
"tey to install applicatons/tools, nearly all you need to do is type one line and" +
" let it finish the rest!</p>\n                    </div>\n                    <div" +
" style=\"float: right; width: 470px; margin: 0 0 24px 0;\">&nbsp;</div>\n          " +
"          <div class=\"MIX-notice\">\n                        <h3 style=\"font-size:" +
" 18px; font-weight: normal;\">Important Notice</h3>\n                        <p st" +
"yle=\"font-size: 14px; line-height: 26px;\">You can develop your own packages and " +
"share them via the Chocolatey Gallery. Read the documentation for more details o" +
"n <a title=\"Creating and submitting a package\" href=\"https://github.com/chocolat" +
"ey/chocolatey/wiki/CreatePackages\">how to create and publish a package</a>. If y" +
"ou don&rsquo;t plan on submitting a package, there&rsquo;s no need to register.<" +
"/p>\n                    </div>\n                </div>\n            </article>\n   " +
"     </div>\n    </div>\n</div>\n");


        }
    }
}
#pragma warning restore 1591
